---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-internet
  namespace: network
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-internet",
      "plugins": [
        {
          "type": "macvlan",
          "master": "enp0s31f6.11",
          "mode": "bridge",
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "172.31.20.0/24", "gw": "172.31.11.254" }
            ]
          }
        }
      ]
    }
