---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-node-feature-discovery
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/ironmaiden/apps/system/node-feature-discovery/app"
  prune: false
  sourceRef:
    kind: GitRepository
    name: ironmaiden
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-node-feature-discovery-rules
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/ironmaiden/apps/system/node-feature-discovery/rules"
  prune: false
  sourceRef:
    kind: GitRepository
    name: ironmaiden
  wait: true
  dependsOn:
    - name: cluster-apps-node-feature-discovery
