---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-flux-monitoring
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/ironmaiden/apps/flux-system/add-ons/monitoring
  prune: false
  sourceRef:
    kind: GitRepository
    name: ironmaiden
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-flux-notifications
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/ironmaiden/apps/flux-system/add-ons/notifications
  prune: false
  sourceRef:
    kind: GitRepository
    name: ironmaiden
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-flux-webhooks
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/ironmaiden/apps/flux-system/add-ons/webhooks
  prune: false
  sourceRef:
    kind: GitRepository
    name: ironmaiden
  wait: true
  dependsOn:
    - name: cluster-apps-external-secrets-stores
