---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mosquitto-src
spec:
  sourcePVC: mosquitto-data
  trigger:
    schedule: "15 */8 * * *"
  restic:
    copyMethod: Snapshot
    repository: mosquitto-restic-secret
    cacheStorageClassName: local-hostpath
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    pruneIntervalDays: 7
    retain:
      daily: 7
      within: 3d
