---
metal:
  children:
    masters:
      hosts:
        metal1: {ansible_host: 172.31.30.11, mac: 'd8:9e:f3:79:4f:ad', disk: nvme0n1, network_interface: enp0s31f6, memsize: 10240, disksize: 64, vlan12_ip: 172.31.12.101, vlan11_ip: 172.31.11.1}
        metal2: {ansible_host: 172.31.30.12, mac: 'd8:9e:f3:79:4d:b6', disk: nvme0n1, network_interface: enp0s31f6, memsize: 10240, disksize: 64, vlan12_ip: 172.31.12.102, vlan11_ip: 172.31.11.2}
        metal3: {ansible_host: 172.31.30.13, mac: '14:b3:1f:25:93:3a', disk: nvme0n1, network_interface: enp0s31f6, memsize: 10240, disksize: 64, vlan12_ip: 172.31.12.103, vlan11_ip: 172.31.11.3}
    workers:
      hosts:
dns:
  hosts:
    # ns1: {ansible_host: 172.31.30.50, mac: 00:50:56:31:30:50, disk: sda, network_interface: ens192}
    # ns2: {ansible_host: 172.31.30.51, mac: 00:50:56:31:30:51, disk: sda, network_interface: ens192}
    ns1: {ansible_host: 172.31.11.88}

minio:
  hosts:
    # VM temporary
    s3: {ansible_host: 172.31.30.60, mac: '00:50:56:31:30:60', disk: sda, network_interface: ens192}
