---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-internet",
                "namespace": "network",
                "ips": ["172.31.11.10/24"]
              },
              {
                "name":"multus-legacy",
                "namespace": "network",
                "ips": ["172.31.12.253/24"]
              }]
          nodeSelector:
            homeassistant.feature.node.kubernetes.io/skyconnect: "true"
          securityContext:
            privileged: true
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2023.11.2
            env:
              SECRET_RECORDER_DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: home-assistant-pguser-home-assistant
                    key: uri
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            securityContext:  # this is required to discover usb devices
              privileged: true
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 47m
                memory: 1254M
              limits:
                memory: 1254M
            
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.18.0
            args:
              - --auth
              - none
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
              - --port
              - "8080"
              - "/config"
            securityContext:
              allowPrivilegeEscalation: false
              runAsUser: 0
          matter-server:
            image:
              repository: ghcr.io/home-assistant-libs/python-matter-server
              tag: 4.0.2

    service:
      main:
        ports:
          http:
            port: 8123
          code-server:
            port: 8080
          matter-server:
            port: 5580
    ingress:
      main:
        enabled: true
        className: "external-nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress-ext.staniek.io
        hosts:
          - host: &host "hass.staniek.io"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
      code-server:
        enabled: true
        className: "internal-nginx"
        hosts:
          - host: &code-host hass-code.staniek.io
            paths:
              - path: /
                service:
                  name: main
                  port: code-server
        tls:
          - hosts:
              - *code-host

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
        advancedMounts:
          main:
            main:
              - path: /config
            code-server:
              - path: /config
                readOnly: false

      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/bus/usb
      deploy-key:
        type: secret
        name: home-assistant-secret
        defaultMode: 256
        globalMounts:
          - path: /root/.ssh/id_rsa
            subPath: GH_DEPLOY_KEY
      # ttyusb:
      #   enabled: true
      #   type: hostPath
      #   # hostPath: /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_7642fecc5541ed11bcf986a7ccf2b06c-if00-port0
      #   hostPath: /dev/ttyUSB0

