clusterName: ENC[AES256_GCM,data:Oa/vzYibTNT64g==,iv:P0Ko7vsS9U1Lg7s1oeB+jfvG0ll+pUEOBffaSlMnpiU=,tag:2jK4A5Xjc8Nwsei7nxhuVw==,type:str]
clusterEndpointIP: ENC[AES256_GCM,data:fG9mlQwWbPxHYYNr,iv:LlXS1jK0XjGV/oiYQRRR3peL0wBpjilJ6B3BIgheRfc=,tag:jEtW7WrsgASwhT4Dtt4iZg==,type:str]
clusterDNSSuffix: ENC[AES256_GCM,data:Y7dK0IMEIHXdvGh7ZDObD8w=,iv:mn/W6hg3pa4c1KzCx/IfLl27/wREQghCIFqOlsh2c2w=,tag:6+OOrxKdvn4Yhf5rXFjIXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mse8y4ju5e22j8trx5hcxsv6hc2tcy3rh2ulney0mqrhtd84rpfqtpxu3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZ2R6dXJrZzRrdXBNN0FF
            MGVxR01sWlhMRWxVcFY2NVJzaXA1T0F2a1ZnCm9nZGtRN1dEbDVZcU5mMWEvRWRL
            OG95OXZsSVZqSWQ0ZG9VRUdSLytiUTAKLS0tIGNsOTc4NVM5MGMySTJhVjVZbHgw
            RHJwRFRYZ3U3UVlwVTFwVWxIbGhWVzQKyAtlj8Om9/owwaenRiQ3nQ+i7PfNHjih
            Genay9dSed8ArMJPqPUgeqT5dxbhax2qnjEQYE4/qgSlfIhmPEUiVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-31T09:34:12Z"
    mac: ENC[AES256_GCM,data:PKY17M1RYFIbYeXlB4dGAb3zSJyvXF/FOA/HShbth0xqOd3AE+BD98Q9XFkbwt0FwRruRiGRsdYxIwMLdVqsnSnAPGcNmpUSNIWwNng2/g4tk7Df//WS3Jt3NVYGTH4NGJD17HngebbFZJC2mcyV3q3kpIrmo7RT/YvqIncyk48=,iv:14a/xqGiFFziNs+yCLjbFYilHZJvcfpoQiKSUiiEAfk=,tag:hjndOrhkkPoOd+vb5QjLzg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
