---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cloudflared
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/ironmaiden/apps/network/cloudflared/app"
  prune: false
  sourceRef:
    kind: GitRepository
    name: ironmaiden
  wait: false
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-externaldns-shared
    - name: cluster-apps-nginx-external
