---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname home-assistant
  namespace: flux-system
spec:
  targetNamespace: home-automation
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/ironmaiden/apps/home-automation/home-assistant/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: ironmaiden
  wait: false
  dependsOn:
    - name: multus-config
    - name: rook-ceph-cluster
    - name: volsync
    - name: external-secrets-stores
    - name: external-secrets-cluster-secrets
    - name: crunchy-postgres-operator
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: hass.staniek.io
      APP_UID: "0"
      APP_GID: "0"
      VOLSYNC_CLAIM: home-assistant-config
      VOLSYNC_ACCESSMODES: ReadWriteMany
      VOLSYNC_STORAGECLASS: ceph-filesystem
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-filesystem
      DB_NAME: home-assistant
      DB_USER: home-assistant

# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &appname home-assistant-code
#   namespace: flux-system
# spec:
#   targetNamespace: home-automation
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *appname
#   path: "./kubernetes/ironmaiden/apps/home-automation/home-assistant/code"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: ironmaiden
#   wait: false
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
#   postBuild:
#     substitute:
#       APP: *appname
#       HOSTNAME: hass-code.staniek.io
#       VOLSYNC_CLAIM: home-assistant-config
