---
# Minio binaries path
minio_server_bin: /usr/local/bin/minio

# Runtime user and group for the Minio server service
minio_user: minio
minio_group: minio

# Minio server data directories
minio_server_datadirs:
  - /var/lib/minio
minio_server_make_datadirs: true

# Path to the file containing the ENV variables for the Minio server
minio_server_envfile: /etc/default/minio

# Minio server listen address
minio_server_addr: ":9091"

# Additional environment variables to be set in minio server environment
minio_server_env_extra: ""

# Additional Minio server CLI options
minio_server_opts: ""

# Minio access and secret keys
minio_access_key: ""
minio_secret_key: ""

minio_root_user: ""
minio_root_password: ""





