---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-tf-controller
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/ironmaiden/apps/infrastructure/tf-controller/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: ironmaiden
  wait: true
  dependsOn:
    - name: cluster-apps-external-secrets-stores
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-tf-controller-terraforms
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/ironmaiden/apps/infrastructure/tf-controller/terraforms"
  prune: true
  sourceRef:
    kind: GitRepository
    name: ironmaiden
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-tf-controller
