---
version: "3"

x-task-vars: &task-vars
  node: "{{.node}}"
  ceph_disk: "{{.ceph_disk}}"
  ts: "{{.ts}}"
  jobName: "{{.jobName}}"

vars:
  waitForJobScript: "../_scripts/wait-for-k8s-job.sh"
  ts: '{{now | date "150405"}}'

tasks:
  get-dashboard-password:
    desc: Display Rook-Ceph dashboard admin password
    silent: true
    cmds:
      - pass=$(kubectl -n rook-ceph get secret rook-ceph-dashboard-password -o jsonpath='{.data.password}' | base64 -d) && echo $pass
  wipe-node-metal1:
    desc: Trigger a wipe of Rook-Ceph data on node "metal1"
    cmds:
      - task: wipe-disk
        vars:
          node: "{{.node}}"
          # ceph_disk: "/dev/disk/by-id/nvme-ADATA_LEGEND_710_2N322L2K45UC"
          ceph_disk: "/dev/nvme0n1"
      - task: wipe-data
        vars:
          node: "{{.node}}"
    vars:
      node: metal1

  wipe-node-metal2:
    desc: Trigger a wipe of Rook-Ceph data on node "metal2"
    cmds:
      - task: wipe-disk
        vars:
          node: "{{.node}}"
          # ceph_disk: "/dev/disk/by-id/nvme-ADATA_LEGEND_710_2N322L1AGAD9"
          ceph_disk: "/dev/nvme0n1"
      - task: wipe-data
        vars:
          node: "{{.node}}"
    vars:
      node: metal2

  wipe-node-metal3:
    desc: Trigger a wipe of Rook-Ceph data on node "metal3"
    cmds:
      - task: wipe-disk
        vars:
          node: "{{.node}}"
          # ceph_disk: "/dev/disk/by-id/nvme-ADATA_LEGEND_710_2N3229A18NUD"
          ceph_disk: "/dev/nvme0n1"
      - task: wipe-data
        vars:
          node: "{{.node}}"
    vars:
      node: metal3

  wipe-disk:
    desc: Wipe all remnants of rook-ceph from a given disk (ex. task rook:wipe-disk node=metal1 ceph_disk="/dev/nvme0n1")
    silent: true
    internal: true
    cmds:
      - envsubst < <(cat {{.wipeRookDiskJobTemplate}}) | kubectl apply -f -
      - echo {{.wipeCephDiskJobName}}
      - bash {{.waitForJobScript}} {{.wipeCephDiskJobName}} default
      - kubectl -n default wait job/{{.wipeCephDiskJobName}} --for condition=complete --timeout=1m
      - kubectl -n default logs job/{{.wipeCephDiskJobName}}
      - kubectl -n default delete job {{.wipeCephDiskJobName}}
    vars:
      node: '{{ or .node (fail "`node` is required") }}'
      ceph_disk: '{{ or .ceph_disk (fail "`ceph_disk` is required") }}'
      jobName: 'wipe-disk-{{- .node -}}-{{- .ceph_disk | replace "/" "-" -}}-{{- .ts -}}'
      wipeCephDiskJobName: 'wipe-disk-{{- .node -}}-{{- .ceph_disk | replace "/" "-" -}}-{{- .ts -}}'
      wipeRookDiskJobTemplate: "WipeDiskJob.tmpl.yaml"
    env: *task-vars
    preconditions:
      - sh: test -f {{.waitForJobScript}}
      - sh: test -f {{.wipeRookDiskJobTemplate}}

  wipe-data:
    desc: Wipe all remnants of rook-ceph from a given disk (ex. task rook:wipe-data node=metal1)
    silent: true
    internal: true
    cmds:
      - envsubst < <(cat {{.wipeRookDataJobTemplate}}) | kubectl apply -f -
      - bash {{.waitForJobScript}} {{.wipeRookDataJobName}} default
      - kubectl -n default wait job/{{.wipeRookDataJobName}} --for condition=complete --timeout=1m
      - kubectl -n default logs job/{{.wipeRookDataJobName}}
      - kubectl -n default delete job {{.wipeRookDataJobName}}
    vars:
      node: '{{ or .node (fail "`node` is required") }}'
      jobName: "wipe-rook-data-{{- .node -}}-{{- .ts -}}"
      wipeRookDataJobName: "wipe-rook-data-{{- .node -}}-{{- .ts -}}"
      wipeRookDataJobTemplate: "WipeRookDataJob.tmpl.yaml"
    env: *task-vars
    preconditions:
      - sh: test -f {{.waitForJobScript}}
      - sh: test -f {{.wipeRookDataJobTemplate}}
