---
- name: Install sops on localhost
  hosts: localhost
  tasks:
    - name: Install sops on localhost
      ansible.builtin.include_role:
        name: community.sops.install
      vars:
        sops_install_on_localhost: true
