---
- name: Configure Pi After Reinstall
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Enable Root Login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#PermitRootLogin'
        line: "PermitRootLogin yes"
        state: present
        backup: true
      become: true
      notify:
        - restart ssh

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
      become: true

  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted
      become: true
