---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: home-assistant-src
spec:
  sourcePVC: home-assistant-config
  trigger:
    schedule: "15 */8 * * *"
  restic:
    copyMethod: Snapshot
    repository: home-assistant-restic-secret
    cacheStorageClassName: local-hostpath
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    pruneIntervalDays: 7
    retain:
      daily: 7
      within: 3d
