---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: home-assistant-dst
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: restore-once
  restic:
    copyMethod: Snapshot
    repository: home-assistant-restic-secret
    cacheStorageClassName: local-hostpath
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    accessModes:
      - ReadWriteOnce
    capacity: 1Gi
