---
- name: Debian | Install Packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Debian | Add interface to default config
  lineinfile:
    dest: /etc/default/isc-dhcp-server
    regexp: '^INTERFACESv4='
    line: 'INTERFACESv4="eth0"'
    state: present
    backup: yes
  notify:
  - restart dhcpd

- name: Debian | Configure Primary DHCP Server
  block:
    - name: Debian | Copy {{ dhcpd_config_file }}
      template: 
        src: "{{ dhcpd_config_file }}.primary.j2"
        dest: "/etc/dhcp/{{ dhcpd_config_file }}"
        owner: root
        group: root
        mode: 0644
      notify:
      - restart dhcpd
  when: "'primary' in group_names"

- name: Debian | Configure Secondary DHCP Server
  block:
    - name: Debian | Copy {{ dhcpd_config_file }}
      template: 
        src: "{{ dhcpd_config_file }}.secondary.j2"
        dest: "/etc/dhcp/{{ dhcpd_config_file }}"
        owner: root
        group: root
        mode: 0644
      notify:
      - restart dhcpd
  when: "'secondary' in group_names"

- name: Debian | Start and Enable Service {{ systemd_service }}
  service:
    name: "{{ systemd_service }}"
    state: started
    enabled: yes
