---
- name: Rocky | Include Secure Vars
  include_vars:
    file: ../defaults/secure.yml

- name: Rocky | Install Packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Rocky | Enable Service {{ firewall_port }} in Firewalld
  firewalld:
    immediate: yes
    service: "{{ firewall_port }}"
    permanent: yes
    state: enabled

- name: Rocky | Enable DHCP Failover Port {{ firewall_dhcp_failover_port }} in Firewalld
  firewalld:
    immediate: yes
    port: "{{ firewall_dhcp_failover_port }}/tcp"
    permanent: yes
    state: enabled

- name: Rocky | Configure Primary DHCP Server
  block:
    - name: Rocky | Copy {{ dhcpd_config_file }}
      template: 
        src: "{{ dhcpd_config_file }}.primary.j2"
        dest: "/etc/dhcp/{{ dhcpd_config_file }}"
        owner: root
        group: root
        mode: 0644
      notify:
      - restart dhcpd
  when: "'dns1' in group_names"

- name: Rocky | Configure Secondary DHCP Server
  block:
    - name: Rocky | Copy {{ dhcpd_config_file }}
      template: 
        src: "{{ dhcpd_config_file }}.secondary.j2"
        dest: "/etc/dhcp/{{ dhcpd_config_file }}"
        owner: root
        group: root
        mode: 0644
      notify:
      - restart dhcpd
  when: "'dns2' in group_names"

- name: Rocky | Start and Enable Service {{ systemd_service }}
  service:
    name: "{{ systemd_service }}"
    state: started
    enabled: yes