---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: scrypted
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/ironmaiden/apps/home-automation/scrypted/app"
  prune: false
  sourceRef:
    kind: GitRepository
    name: ironmaiden
  wait: false
  dependsOn:
    # - name: multus-config
    - name: rook-ceph-cluster
    - name: volsync
    - name: external-secrets-stores
