---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-externaldns-shared
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/ironmaiden/apps/network/external-dns/shared"
  prune: true
  sourceRef:
    kind: GitRepository
    name: ironmaiden
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-externaldns-external
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/ironmaiden/apps/network/external-dns/external"
  prune: true
  sourceRef:
    kind: GitRepository
    name: ironmaiden
  wait: true
  dependsOn:
    - name: cluster-apps-externaldns-shared
    - name: cluster-apps-external-secrets-stores
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-externaldns-internal
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/ironmaiden/apps/network/external-dns/internal"
  prune: true
  sourceRef:
    kind: GitRepository
    name: ironmaiden
  wait: true
  dependsOn:
    - name: cluster-apps-external-secrets-stores
