---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./volsync
  - ./pvc.yaml
  - ./pvc-nfs.yaml
  - ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: scrypted
  app.kubernetes.io/instance: scrypted
