---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrypted-config
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: scrypted-dst
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-block
