---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-traefik
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/ironmaiden/apps/network/ingress-traefik/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: ironmaiden
  wait: false # no flux ks dependents
