---
- name: VMWare | Include Secure Vars
  include_vars:
    file: ../defaults/secure.yml

- name: VMWare | Get list of accounts
  command: "esxcli system account list"
  register: account_list

- name: VMWare | Create users
  include_tasks: create_users.yml  
  loop: "{{ users }}"
  loop_control:
    loop_var: outer_item

    