---
k3s_version: v1.28.2+k3s1
k3s_config_file: /etc/rancher/k3s/config.yaml
k3s_token_file: /etc/rancher/node/password
k3s_service_file: /etc/systemd/system/k3s.service
k3s_server_config:
  disable:
    - traefik
    - servicelb
    - metrics-server
    - local-storage
  disable-cloud-controller: true
  secrets-encryption: true
  flannel-backend: none
  disable-network-policy: true
  disable-kube-proxy: true
