---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname volsync
  namespace: flux-system
spec:
  targetNamespace: system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/ironmaiden/apps/system/volsync/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: ironmaiden
  dependsOn:
    - name: snapshot-controller
    - name: rook-ceph-cluster
  wait: false
  timeout: 2m
