---
data_dir: /vector-data-dir

api:
  enabled: true
  address: 0.0.0.0:8686

enrichment_tables:
  geoip_table:
    type: geoip
    path: /usr/share/GeoIP/GeoLite2-City.mmdb

# Sources
sources:
  kubernetes_source:
    address: 0.0.0.0:6000
    type: vector
    version: "2"

  cisco_syslog:
    type: syslog
    mode: udp
    address: 0.0.0.0:514

  journald_source:
    type: vector
    address: 0.0.0.0:6002
    version: "2"

# Transformations
transforms:
  filter_severity:
    type: "filter"
    inputs:
      - cisco_syslog
    condition: |
      !includes(["debug"], .severity)

  kubernetes_remap:
    type: remap
    inputs:
      - kubernetes_source
    source: |
      # Standardize 'app' index
      .custom_app_name = .pod_labels."app.kubernetes.io/name" || .pod_labels.app || .pod_labels."k8s-app" || "unknown"
      # Drop pod_labels
      del(.pod_labels)

# Sinks
sinks:
  loki_kubernetes:
    type: loki
    inputs:
      - kubernetes_remap
    endpoint: http://loki-gateway.monitoring.svc.cluster.local
    encoding:
      codec: json
    out_of_order_action: rewrite_timestamp
    remove_label_fields: true
    remove_timestamp: true
    labels:
      "*": "{{ metadata }}"
      "pod_labels_*": "{{ kubernetes.pod_labels }}"
      source: vector
      "{{ event_field }}": "{{ some_other_event_field }}"
    # labels:
    #   app: "{{ custom_app_name }}"
    #   namespace: "{{ kubernetes.pod_namespace }}"
    #   node: "{{ kubernetes.pod_node_name }}"

  loki_cisco:
    type: loki
    inputs:
      - filter_severity
    endpoint: http://loki-gateway.monitoring.svc.cluster.local
    encoding:
      codec: json
    out_of_order_action: rewrite_timestamp
    labels:
      hostname: "{{ host }}"

  loki_journal:
    type: loki
    endpoint: http://loki-gateway.monitoring.svc.cluster.local.
    encoding:
      codec: json
    inputs:
      - journald_source
    out_of_order_action: accept
    remove_label_fields: true
    remove_timestamp: true
    labels:
      hostname: "{{ host }}"
