---
- name: Generate Subnet4
  set_fact:
    subnet4: "{{ subnet4 | default([]) + [{ 'subnet': item.dhcp.subnet, 'pools': [{'pool': item.dhcp.range.start + ' - ' + item.dhcp.range.end}], 'option-data': item.dhcp.options }] }}"
  with_items: "{{network_topology.networks}}"
  when: item.dhcp | default(false)
- debug: msg="{{ subnet4 | to_json(indent=4) }}"
- name: Generate kea dhcp4 config
  ansible.builtin.template:
    src: kea-dhcp4.conf.j2
    dest: "{{ role_path }}/files/kea-dhcp4.conf"
    mode: 0644
  delegate_to: localhost
