---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-multus
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/ironmaiden/apps/network/multus/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: ironmaiden
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-multus-config
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/ironmaiden/apps/network/multus/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: ironmaiden
  wait: true
  dependsOn:
    - name: cluster-apps-multus
