---
- name: VMWare | Copy SSL fullchain
  ansible.builtin.copy:
    src: files/fullchain.pem
    dest: /etc/vmware/ssl/rui.crt
    mode: '0644'
    backup: yes

- name: VMWare | Copy SSL privkey
  ansible.builtin.copy:
    src: files/privkey.pem
    dest: /etc/vmware/ssl/rui.key
    mode: '0400'
    backup: yes

- name: VMWare | Restart Services
  command: services.sh restart

