---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "staniek-io"
  namespace: network
spec:
  secretName: "staniek-io-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "staniek.io"
  dnsNames:
    - "staniek.io"
    - "*.staniek.io"
