---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: scrypted-nfs
provisioner: nfs
parameters:
  archiveOnDelete: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scrypted-nfs
spec:
  storageClassName: scrypted-nfs
  capacity:
    storage: 1Mi # Size does not matter
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: shaun.home.staniek.name
    path: /share/nfs/Apps/scrypted
  mountOptions:
    - nfsvers=3
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrypted-nfs
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: scrypted-nfs
  resources:
    requests:
      storage: 1Mi # Size does not matter
